package in.swifiic.android.app.lib.ui;

import in.swifiic.android.app.lib.Constants;
import in.swifiic.android.app.lib.GenericService;
import android.app.Activity;
import android.content.BroadcastReceiver;
import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.content.ServiceConnection;
import android.os.IBinder;


public class SwifiicActivity extends Activity {
	protected GenericService mService = null;
    private boolean mBound = false;

    protected BroadcastReceiver mDataReceiver = null;
    
	@Override
	protected void onDestroy() {
        // unbind from service
        if (mBound) {
            // unbind from the MsngrService
            unbindService(mConnection);
            mBound = false;
        }
        
		super.onDestroy();
	}
	

    private ServiceConnection mConnection = new ServiceConnection() {
        public void onServiceConnected(ComponentName name, IBinder service) {
            mService = ((GenericService.LocalBinder)service).getService();
        }

        public void onServiceDisconnected(ComponentName name) {
            mService = null;
        }
    };
    
	
    @Override
    public void onPause() {
        super.onPause();
        
        // unregister the receiver for the DATA_UPDATED intent
        unregisterReceiver(mDataReceiver);
    }

    @Override
    public void onResume() {
        super.onResume();
        
        if (!mBound) {
            // bind to the MsngrService
            bindService(new Intent(this, GenericService.class), mConnection, Context.BIND_AUTO_CREATE);
            mBound = true;
        }
        
        // register an receiver for NEWMSG_RECEIVED intent generated by the MsngrService
        IntentFilter filter = new IntentFilter(Constants.NEWMSG_RECEIVED);
        registerReceiver(mDataReceiver, filter);
    }
    
	
}
